package model.entity; // Package declaration based on your project structure

import java.math.BigDecimal; // Import for BigDecimal

public class DiscoDuro extends Componente {
    private String marca;
    private String modelo;
    private String capacidad; // Changed from cantidadAlmacenamiento for consistency
    private String tipoConexion;

    // Constructor for existing components (with ID from DB)
    public DiscoDuro(int componenteID, String numeroSerie, BigDecimal precio, int cantidadDisponible,
            String marca, String modelo, String capacidad, String tipoConexion) {
        super(componenteID, numeroSerie, "DiscoDuro", precio, cantidadDisponible);
        this.marca = marca;
        this.modelo = modelo;
        this.capacidad = capacidad;
        this.tipoConexion = tipoConexion;
    }

    // Constructor for new components (without ID, will be generated by DB)
    public DiscoDuro(String numeroSerie, BigDecimal precio, int cantidadDisponible,
            String marca, String modelo, String capacidad, String tipoConexion) {
        super(numeroSerie, "DiscoDuro", precio, cantidadDisponible);
        this.marca = marca;
        this.modelo = modelo;
        this.capacidad = capacidad;
        this.tipoConexion = tipoConexion;
    }

    // Getters and Setters for specific attributes
    @Override
    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    @Override
    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getCapacidad() {
        return capacidad;
    }

    public void setCapacidad(String capacidad) {
        this.capacidad = capacidad;
    }

    public String getTipoConexion() {
        return tipoConexion;
    }

    public void setTipoConexion(String tipoConexion) {
        this.tipoConexion = tipoConexion;
    }
}
