package model.entity; // Package declaration based on your project structure

import java.math.BigDecimal; // Import for BigDecimal

public class MemoriaRAM extends Componente { // Renamed from Ram to MemoriaRAM for clarity
    private String marca;
    private String capacidad; // Changed from cantidadMemoria for consistency
    private String tipoMemoria;

    // Constructor for existing components (with ID from DB)
    public MemoriaRAM(int componenteID, String numeroSerie, BigDecimal precio, int cantidadDisponible,
            String marca, String capacidad, String tipoMemoria) {
        super(componenteID, numeroSerie, "MemoriaRAM", precio, cantidadDisponible);
        this.marca = marca;
        this.capacidad = capacidad;
        this.tipoMemoria = tipoMemoria;
    }

    // Constructor for new components (without ID, will be generated by DB)
    public MemoriaRAM(String numeroSerie, BigDecimal precio, int cantidadDisponible,
            String marca, String capacidad, String tipoMemoria) {
        super(numeroSerie, "MemoriaRAM", precio, cantidadDisponible);
        this.marca = marca;
        this.capacidad = capacidad;
        this.tipoMemoria = tipoMemoria;
    }

    // Getters and Setters for specific attributes
    @Override
    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    @Override
    public String getModelo() {
        // MemoriaRAM typically doesn't have a 'Modelo' like CPU/MB, so return null or
        // empty string
        return null; // Or return "";
    }

    public String getCapacidad() {
        return capacidad;
    }

    public void setCapacidad(String capacidad) {
        this.capacidad = capacidad;
    }

    public String getTipoMemoria() {
        return tipoMemoria;
    }

    public void setTipoMemoria(String tipoMemoria) {
        this.tipoMemoria = tipoMemoria;
    }
}
