package model.entity; // Package declaration based on your project structure

import java.math.BigDecimal; // Import for BigDecimal

public class Microprocesador extends Componente {
    private String marca;
    private String modelo;
    private String socket; // Changed from tipoConector for consistency with DB schema
    private String velocidad; // Changed from velocidadPorcesamiento for consistency

    // Constructor for existing components (with ID from DB)
    public Microprocesador(int componenteID, String numeroSerie, BigDecimal precio, int cantidadDisponible,
            String marca, String modelo, String socket, String velocidad) {
        super(componenteID, numeroSerie, "Microprocesador", precio, cantidadDisponible);
        this.marca = marca;
        this.modelo = modelo;
        this.socket = socket;
        this.velocidad = velocidad;
    }

    // Constructor for new components (without ID, will be generated by DB)
    public Microprocesador(String numeroSerie, BigDecimal precio, int cantidadDisponible,
            String marca, String modelo, String socket, String velocidad) {
        super(numeroSerie, "Microprocesador", precio, cantidadDisponible);
        this.marca = marca;
        this.modelo = modelo;
        this.socket = socket;
        this.velocidad = velocidad;
    }

    // Getters and Setters for specific attributes
    @Override
    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    @Override
    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getSocket() {
        return socket;
    }

    public void setSocket(String socket) {
        this.socket = socket;
    }

    public String getVelocidad() {
        return velocidad;
    }

    public void setVelocidad(String velocidad) {
        this.velocidad = velocidad;
    }
}
