package model.entity; // Package declaration based on your project structure

import java.math.BigDecimal; // Import for BigDecimal

public class TarjetaMadre extends Componente {
    private String marca;
    private String modelo;
    private String socketMicro; // Changed from tipoConector for consistency with DB schema
    private String tipoMemoriaRam;
    private String conexionesDisco; // Added for consistency with DB schema

    // Constructor for existing components (with ID from DB)
    public TarjetaMadre(int componenteID, String numeroSerie, BigDecimal precio, int cantidadDisponible,
            String marca, String modelo, String socketMicro, String tipoMemoriaRam, String conexionesDisco) {
        super(componenteID, numeroSerie, "TarjetaMadre", precio, cantidadDisponible);
        this.marca = marca;
        this.modelo = modelo;
        this.socketMicro = socketMicro;
        this.tipoMemoriaRam = tipoMemoriaRam;
        this.conexionesDisco = conexionesDisco;
    }

    // Constructor for new components (without ID, will be generated by DB)
    public TarjetaMadre(String numeroSerie, BigDecimal precio, int cantidadDisponible,
            String marca, String modelo, String socketMicro, String tipoMemoriaRam, String conexionesDisco) {
        super(numeroSerie, "TarjetaMadre", precio, cantidadDisponible);
        this.marca = marca;
        this.modelo = modelo;
        this.socketMicro = socketMicro;
        this.tipoMemoriaRam = tipoMemoriaRam;
        this.conexionesDisco = conexionesDisco;
    }

    // Getters and Setters for specific attributes
    @Override
    public String getMarca() {
        return marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    @Override
    public String getModelo() {
        return modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getSocketMicro() {
        return socketMicro;
    }

    public void setSocketMicro(String socketMicro) {
        this.socketMicro = socketMicro;
    }

    public String getTipoMemoriaRam() {
        return tipoMemoriaRam;
    }

    public void setTipoMemoriaRam(String tipoMemoriaRam) {
        this.tipoMemoriaRam = tipoMemoriaRam;
    }

    public String getConexionesDisco() {
        return conexionesDisco;
    }

    public void setConexionesDisco(String conexionesDisco) {
        this.conexionesDisco = conexionesDisco;
    }
}
